--- 
:urls:
- http://d36jn9qou1tztq.cloudfront.net/static_war/render/css/packed/pack5.css.373145863781
- http://d36jn9qou1tztq.cloudfront.net/static_war/render/css/packed/noaccessibility.css.426842630073
- http://dwfwn5ehtp58w.cloudfront.net/static_war/render/css/packed/noaccessibility.css.426842630073
:dns_servers:
- 8.8.8.8
- 8.8.4.4
